[package]
name = "wast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer="3.0"
sdl2="0.35"
curl="0.4"
url="2.3"
